#! /bin/sh
PYTHON_SCRIPTS_PATH="$( dirname "${BASH_SOURCE[0]}" )/python_scripts"
run_python(){
  python2 "$PYTHON_SCRIPTS_PATH/$1.py" "${@:2}"
}

CACHE_FILE="/tmp/i3blocklet-time/timezones-$(printf '%(%Y-%m-%d)T')"
if test -f "$CACHE_FILE"; then
  TIMEZONEINFO="$(cat $CACHE_FILE)"
else
  CACHE_FOLDER=$(dirname $CACHE_FILE)
  rm -rf $CACHE_FOLDER/timezones*
  mkdir -p $CACHE_FOLDER
  TIMEZONEINFO="$( cat /usr/share/zoneinfo/zone.tab \
    | grep -v "^#" \
    | awk '{print $3" "$2}' \
    | sed -r -e 's/ ([+-][0-9]{2})([0-9]+)([+-][0-9]{3})/ \1.\2 \3./' -e 's/ ([+-])0+/ \1/g' \
    | while read -r tz la lo; do TZ="$tz" printf "$tz"' %(%z %Z)T '"$la $lo"'\n' -1;done \
    | run_python addSunTimes \
    | sort -g -k2,2 \
    | sed -r 's/([+-][0-9]{2})([0-9]{2})/\1:\2/' \
    | tee $CACHE_FILE )"
fi

FORMAT_COLUMNS=${timezone_columns:-'name,time,offset,abbreviation,latitude,longitude,sunrise,sunset'}
ROFI_CONTENT=$(echo "$TIMEZONEINFO" \
  | run_python format "$FORMAT_COLUMNS"  \
  | column -s ';' -t \
  )


ROFI_HEADER=$(echo "$ROFI_CONTENT" |  head -1)
TIMESTATUS="$(timedatectl status )"
MESSAGE="$TIMESTATUS"$'\n'"$ROFI_HEADER"
let "WIDTH = $(wc -L <<< "$MESSAGE") + 4"


ROFI_OPTIONAL_ARGS=()
if ! [[ -z "$rofi_theme" ]]; then
  ROFI_OPTIONAL_ARGS+=( -theme "$rofi_theme" )
fi
if ! [[ -z "$rofi_window_anchor" ]]; then
  ROFI_OPTIONAL_ARGS+=( -theme-str '#window {anchor:'"$rofi_window_anchor"';}' )
fi



SELECTED_OPTION="$(echo "$ROFI_CONTENT" \
	| tail +2 \
  | rofi -dmenu -m -3 -mesg "$MESSAGE" -eh 1 -width -$WIDTH -markup-rows -p "Select timezone" "${ROFI_OPTIONAL_ARGS[@]}" \
)"   

if [ ! -z "$SELECTED_OPTION" ]
then
    SELECTED_TIMEZONE="$(cut -d" " -f1 <<< "$SELECTED_OPTION")"
 	sudo timedatectl set-timezone "$SELECTED_TIMEZONE"
fi