#!/bin/env bash
PYTHON_SCRIPTS_PATH="$( dirname "${BASH_SOURCE[0]}" )/python_scripts"
pyscript(){
  python3 "$PYTHON_SCRIPTS_PATH/$1.py" "${@:2}"
}

FORMAT_COLUMNS=name,${additional_columns:-'time,offset,abbreviation,latitude,longitude,sunrise,sunset'}

function getTimezonesWithSunTimes(){
  CACHE_FILE="/tmp/i3blocklet-time/timezones-$(printf '%(%Y-%m-%d)T')"
  if test -f "$CACHE_FILE"; then
    cat $CACHE_FILE
  else
    mkdir -p $(dirname $CACHE_FILE)
    cat /usr/share/zoneinfo/zone.tab \
      | grep -v "^#" \
      | awk '{print $3" "$2}' \
      | pyscript addSunTimes \
      | pyscript appendTzAbbrOffsets -f 1 --sort \
      | tee $CACHE_FILE
  fi
}

TABLE=$(getTimezonesWithSunTimes | pyscript format "$FORMAT_COLUMNS"  | column -s ';' -t )
TABLE_HEADER="${TABLE%%$'\n'*}"
TABLE_LINES="${TABLE#*$'\n'}"
TIMESTATUS="$(timedatectl status )"
MESSAGE="$TIMESTATUS"$'\n'"$TABLE_HEADER"
WIDTH=$(bc <<< "( $(wc -L <<< "$MESSAGE") * 1.05 )/1" )


ROFI_ARGS=(-dmenu -mesg "$MESSAGE" -eh 1 -markup-rows -p "Select timezone")
if ! [[ -z "$rofi_theme" ]]; then
  ROFI_ARGS+=( -theme "$rofi_theme" )
fi
if ! [[ -z "$rofi_window_anchor" ]]; then
  ROFI_ARGS+=( -m -3 -theme-str '#window {anchor:'"$rofi_window_anchor"'; width: '"$WIDTH"'ch; }' )
fi

SELECTED_OPTION="$(rofi "${ROFI_ARGS[@]}" <<< "$TABLE_LINES" )"   

if [ ! -z "$SELECTED_OPTION" ]
then
  SELECTED_TIMEZONE="$(cut -d" " -f1 <<< "$SELECTED_OPTION")"
 	timedatectl set-timezone "$SELECTED_TIMEZONE"
fi