#! /bin/sh
PYTHON_SCRIPTS_PATH="$( dirname "${BASH_SOURCE[0]}" )/python_scripts"
pyscript(){
  python3 "$PYTHON_SCRIPTS_PATH/$1.py" "${@:2}"
}

FORMAT_COLUMNS=${timezone_columns:-'name,time,offset,abbreviation,latitude,longitude,sunrise,sunset,latitude:decimal,longitude:decimal'}

function getTimezonesWithSunTimes(){
  CACHE_FILE="/tmp/i3blocklet-time/timezones-$(printf '%(%Y-%m-%d)T')"
  if test -f "$CACHE_FILE"; then
    cat $CACHE_FILE
  else
    mkdir -p $(dirname $CACHE_FILE)
    cat /usr/share/zoneinfo/zone.tab \
      | grep -v "^#" \
      | awk '{print $3" "$2}' \
      | pyscript addSunTimes \
      | pyscript appendTzAbbrOffsets --sort \
      | tee $CACHE_FILE
  fi
}


ROFI_CONTENT=$(getTimezonesWithSunTimes | pyscript format "$FORMAT_COLUMNS"  | column -s ';' -t )
ROFI_HEADER=$(echo "$ROFI_CONTENT" |  head -1)
TIMESTATUS="$(timedatectl status )"
MESSAGE="$TIMESTATUS"$'\n'"$ROFI_HEADER"
WIDTH="$(echo "( $(wc -L <<< "$MESSAGE") * 1.05 )/1" | bc)"


ROFI_OPTIONAL_ARGS=()
if ! [[ -z "$rofi_theme" ]]; then
  ROFI_OPTIONAL_ARGS+=( -theme "$rofi_theme" )
fi
if ! [[ -z "$rofi_window_anchor" ]]; then
  ROFI_OPTIONAL_ARGS+=( -m -3 -theme-str '#window {anchor:'"$rofi_window_anchor"';}' )
fi



SELECTED_OPTION="$(echo "$ROFI_CONTENT" \
	| tail +2 \
  | rofi -dmenu -mesg "$MESSAGE" -eh 1 -width -$WIDTH -markup-rows -p "Select timezone" "${ROFI_OPTIONAL_ARGS[@]}" \
)"   

if [ ! -z "$SELECTED_OPTION" ]
then
    SELECTED_TIMEZONE="$(cut -d" " -f1 <<< "$SELECTED_OPTION")"
 	sudo timedatectl set-timezone "$SELECTED_TIMEZONE"
fi